### ISSUE TITLE
[Question/Feature Request] - Support Accented Characters/Letters

### ISSUE THREAD

**Issue by kylehandy123** [Schaka/janitorr#57] opened 2024-08-31 00:55 UTC
Hi Schaka,
I'm not sure if this is even possible, but is it possible to support accented characters/letters in show/movie names? I noticed Janitorr didn't like the fact that for the show Shogun, the actual title and folder/series name is Shōgun. 

Not a huge deal. I just wanted to bring it to attention in case this is something that isn't too difficult to fix.

**Comment by Schaka** [comment] 2024-08-31 06:55
In what way? Janitorr is completely agnostic when it comes to naming. The JVM uses UTF-16 internally for strings and I don't do anything special around that. 

Provide a `TRACE` log if something isn't working as expected, please.
You can do `docker logs janitorr > log.txt`.

Janitorr gets folder names from Sonarr/Radarr and just creates an exact copy of them. I've never had a problem with that, including media that may contain special characters.

**Comment by Schaka** [comment] 2024-09-09 13:45
I'm gonna have to close this as cannot reproduce. I specifically tried with that show (same spelling) and everything worked out just fine.

**Closed by Schaka** 2024-09-09 13:45 UTC
