### ISSUE TITLE
External disk

### ISSUE THREAD

**Issue by Sergiomg86** [Schaka/janitorr#35] opened 2024-04-15 14:13 UTC
Good.

After the last update of janitorr (or so I think) I have seen that it is checking the free space of the ssd card and not of the 4b external disk.

Is there something wrong with the configuration? the real external disk has 75% of free space and the janitorr log is giving me this information

This is my yml

```
version: '3'

services:
  janitorr:
    container_name: janitorr
    image: ghcr.io/schaka/janitorr:latest
    volumes:
      - /appdata/janitorr/config:/config
      - /externo/media:/data #external disk
```

And the log:
```
time="2024-04-15T16:10:51+02:00" level=warning msg="/compose/janitorr/janitorr.yml: `version` is obsolete"
[2Kjanitorr  | 
[2Kjanitorr  |   .   ____          _            __ _ _
[2Kjanitorr  |  /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
[2Kjanitorr  | ( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
[2Kjanitorr  |  \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
[2Kjanitorr  |   '  |____| .__|_| |_|_| |_\__, | / / / /
[2Kjanitorr  |  =========|_|==============|___/=/_/_/_/
[2Kjanitorr  |  :: Spring Boot ::                (v3.2.4)
[2Kjanitorr  | 
[2Kjanitorr  | 2024-04-15T14:05:44.085Z  INFO 1 --- [           main] c.g.s.janitorr.JanitorrApplicationKt     : Starting JanitorrApplicationKt using Java 21.0.2 with PID 1 (/app/classes started by root in /)
[2Kjanitorr  | 2024-04-15T14:05:44.088Z  INFO 1 --- [           main] c.g.s.janitorr.JanitorrApplicationKt     : No active profile set, falling back to 1 default profile: "default"
[2Kjanitorr  | 2024-04-15T14:05:45.855Z  INFO 1 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port 8978 (http)
[2Kjanitorr  | 2024-04-15T14:05:45.879Z  INFO 1 --- [           main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
[2Kjanitorr  | 2024-04-15T14:05:45.879Z  INFO 1 --- [           main] o.apache.catalina.core.StandardEngine    : Starting Servlet engine: [Apache Tomcat/10.1.19]
[2Kjanitorr  | 2024-04-15T14:05:45.960Z  INFO 1 --- [           main] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
[2Kjanitorr  | 2024-04-15T14:05:45.962Z  INFO 1 --- [           main] w.s.c.ServletWebServerApplicationContext : Root WebApplicationContext: initialization completed in 1769 ms
[2Kjanitorr  | 2024-04-15T14:05:47.701Z  INFO 1 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat started on port 8978 (http) with context path ''
[2Kjanitorr  | 2024-04-15T14:05:47.719Z  INFO 1 --- [           main] c.g.s.janitorr.JanitorrApplicationKt     : Started JanitorrApplicationKt in 4.088 seconds (process running for 4.383)
[2Kjanitorr  | 2024-04-15T14:05:47.764Z  INFO 1 --- [   scheduling-1] c.g.s.j.cleanup.AbstractCleanupSchedule  : Not deleting Shows because minimum disk threshold was not reached.
[2Kjanitorr  | 2024-04-15T14:05:47.766Z  INFO 1 --- [   scheduling-1] c.g.s.j.cleanup.AbstractCleanupSchedule  : Free disk space: 96.8256611364117%
[2Kjanitorr  | 2024-04-15T14:05:47.766Z  INFO 1 --- [   scheduling-1] c.g.s.j.cleanup.AbstractCleanupSchedule  : Not deleting Movies because minimum disk threshold was not reached.
[2Kjanitorr  | 2024-04-15T14:05:47.766Z  INFO 1 --- [   scheduling-1] c.g.s.j.cleanup.AbstractCleanupSchedule  : Free disk space: 96.8256611364117%
```

![external disk](https://github.com/Schaka/janitorr/assets/162694116/08cca1a8-898e-40f7-902f-1c9a94d2fbdd)

Do you know why it is not taking the external disk, the yml paths are in the right place?

Regards.

**Comment by Schaka** [comment] 2024-04-15 15:30
Janitorr checks free space on your root path `/` by default. However that is mapped into the container is how it will calculate disk space.

If you look at the [template](https://github.com/Schaka/janitorr/blob/develop/src/main/resources/application-template.yml) here, you'll see that you can tell it EXACTLY which directory to use for the calculation.

You are free to map anything you want into a certain directory, for example:
```
volumes:
      - /appdata/janitorr/config:/config
      - /externo/media:/data #external disk
      - /externo/media:/space/external
      - /internal/whatever:/space/internal
```

Then set the directory:
```
file-system:
  access: true
  free-space-check-dir: "/space" # used to calculate free space
```

**Comment by Schaka** [comment] 2024-04-19 16:19
Closing this, I believe my explanation is enough. I definitely can't reproduce this at all.

**Closed by Schaka** 2024-04-19 16:19 UTC
